name: GHCR Element Web Deploy

on:
  push:
    branches:
      - main
    paths:
      - docker-web/**
  workflow_dispatch:

permissions: write-all

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v5

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Inventory Image'
        run: |
          cd docker
          docker build . --no-cache --tag ghcr.io/govuk-digital-backbone/element-web:latest
          docker push ghcr.io/govuk-digital-backbone/element-web:latest
